apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: DEPLOY_ENV
  labels:
    name: redis-master
spec:
  ports:
    - port: 6379
  selector:
    redis-master: "true"

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: DEPLOY_ENV
  labels:
    name: redis-master
spec:
  serviceName: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        redis-master: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: harbor.missfresh.net/library/redis:ha-sentinel
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-master-volume
          mountPath: /redis-master-data
      imagePullSecrets: ## 腾讯云上访问私有仓库使用的secret，不需修改
        - name: registry-secret
        - name: qcloudregistrykey
        - name: tencenthubkey
  volumeClaimTemplates:
  - metadata:
      name: redis-master-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "cbs"  #存储类名，改为集群中已存在的
      resources:
        requests:
          storage: 5Gi