apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: DEPLOY_ENV
type: Opaque
data:
  # echo -n "6V76CR20EOGse*ZL5lmwMYdyqrotHQ"|base64
  redis-password: NlY3NkNSMjBFT0dzZSpaTDVsbXdNWWR5cXJvdEhR