# dev
dev:
  Script:
    Start: "/Users/Heyu/data/start.sh"
    Shutdown: "/Users/Heyu/data/shutdown.sh"
    Restart: "/Users/Heyu/data/restart.sh"
    Env: "/Users/Heyu/data/env.sh"
    JarBeta: "/Users/Heyu/data/start_jar.sh"
    JettyBeta: "/Users/Heyu/data/start_jetty.sh"
    TomcatBeta: "/Users/Heyu/data/start_tomcat.sh"
    GoBeta: "/Users/Heyu/data/start_go.sh"
    PythonBeta: "/Users/Heyu/data/start_python.sh"
    StaticBeta: "/Users/Heyu/data/start_static.sh"
    WmsBeta: "/data/app/ops-client-script/start_wms.sh"
    JarRelease: "/Users/Heyu/data/start_jar.sh"
    JettyRelease: "/Users/Heyu/data/start_jetty.sh"
    TomcatRelease: "/Users/Heyu/data/start_tomcat.sh"
    GoRelease: "/Users/Heyu/data/start_go.sh"
    PythonRelease: "/Users/Heyu/data/start_python.sh"
    StaticRelease: "/Users/Heyu/data/start_static.sh"
    WmsRelease: "/data/app/ops-client-script/start_wms.sh"
  Url:
    ReportUrl: "http://127.0.0.1:18090/api/publish/agent/receive"
# beta
beta:
  Script:
    Start: "/data/scripts/matrix-scripts/agent/start.sh"
    Shutdown: "/data/scripts/matrix-scripts/agent/shutdown.sh"
    Restart: "/data/scripts/matrix-scripts/agent/restart.sh"
    Env: "/data/scripts/matrix-scripts/agent/env.sh"
    JarBeta: "/data/app/ops-client-script/ops_boot.sh"
    JettyBeta: "/data/app/ops-client-script/ops_boot.sh"
    TomcatBeta: "/data/scripts/matrix-scripts/agent/start_tomcat.sh"
    GoBeta: "/data/app/ops-client-script/temp_start_ess_go.sh"
    PythonBeta: "/data/scripts/matrix-scripts/agent/start_python.sh"
    StaticBeta: "/data/scripts/matrix-scripts/agent/start_static.sh"
    WmsBeta: "/data/app/ops-client-script/start_wms.sh"
    JarRelease: "/data/app/ops-client-script/ops_boot.sh"
    JettyRelease: "/data/scripts/matrix-scripts/agent/start_jetty.sh"
    TomcatRelease: "/data/scripts/matrix-scripts/agent/start_tomcat.sh"
    GoRelease: "/data/app/ops-client-script/temp_start_ess_go.sh"
    PythonRelease: "/data/scripts/matrix-scripts/agent/start_python.sh"
    StaticRelease: "/data/scripts/matrix-scripts/agent/start_static.sh"
    WmsRelease: "/data/app/ops-client-script/start_wms.sh"
  Url:
    ReportUrl: "http://127.0.0.1:18090/api/publish/agent/receive"
# release
release:
  Script:
    Start: "/data/scripts/matrix-scripts/agent/start.sh"
    Shutdown: "/data/scripts/matrix-scripts/agent/shutdown.sh"
    Restart: "/data/scripts/matrix-scripts/agent/restart.sh"
    Env: "/data/scripts/matrix-scripts/agent/env.sh"
    JarBeta: "/data/app/ops-client-script/ops_boot.sh"
    JettyBeta: "/data/app/ops-client-script/ops_boot.sh"
    TomcatBeta: "/data/scripts/matrix-scripts/agent/beta/start_tomcat.sh"
    GoBeta: "/data/app/ops-client-script/temp_start_ess_go.sh"
    PythonBeta: "/data/scripts/matrix-scripts/agent/beta/start_python.sh"
    StaticBeta: "/data/scripts/matrix-scripts/agent/beta/start_static.sh"
    WmsBeta: "/data/app/ops-client-script/start_wms.sh"
    JarRelease: "/data/app/ops-client-script/ops_boot.sh"
    JettyRelease: "/data/scripts/matrix-scripts/agent/release/start_jetty.sh"
    TomcatRelease: "/data/scripts/matrix-scripts/agent/release/start_tomcat.sh"
    GoRelease: "/data/app/ops-client-script/temp_start_ess_go.sh"
    PythonRelease: "/data/scripts/matrix-scripts/agent/release/start_python.sh"
    StaticRelease: "/data/scripts/matrix-scripts/agent/release/start_static.sh"
    WmsRelease: "/data/app/ops-client-script/start_wms.sh"
  Url:
    ReportUrl: "http://127.0.0.1:18090/api/publish/agent/receive"